export const DB_ENV_KEYS = {
  HOST: 'DATABASE_HOST',
  PORT: 'DATABASE_PORT',
  USERNAME: 'DATABASE_USERNAME',
  PASSWORD: 'DATABASE_PASSWORD',
  NAME: 'DATABASE_NAME',
  URL: 'DATABASE_URL',
} as const;
