export const JWT_ENV_KEYS = {
  ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  ACCESS_EXPIRES: 'JWT_ACCESS_EXPIRES',
  REFRESH_EXPIRES: 'JWT_REFRESH_EXPIRES',
} as const;